package com.hellblazer.primeMover.classfile;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Test suite for SimulationTransform to ensure it produces structurally equivalent results to both the original
 * SimulationTransformOriginal and SimulationTransformRefactored implementations.
 */
public class SimulationTransformTest {

    private SimulationTransform classFileTransform;

    @BeforeEach
    public void setUp() throws Exception {
        var scanner = new ClassScanner()
            .addClasspathEntry(Path.of("target/test-classes"))
            .addClasspathEntry(Path.of("target/classes"))
            .scan();
        classFileTransform = new SimulationTransform(scanner);
    }

    @AfterEach
    public void tearDown() throws Exception {
        if (classFileTransform != null) {
            classFileTransform.close();
        }
    }

    @Test
    public void testClassFileTransformFunctionality() throws Exception {
        // Test that ClassFile API transform provides all expected functionality
        final var className = "com.hellblazer.primeMover.classfile.testClasses.MyTest";

        // Test generatorOf
        var generator = classFileTransform.generatorOf(className);
        assertNotNull(generator, "Should create generator for known entity class");

        // Test generators
        var generators = classFileTransform.generators();
        assertTrue(generators.size() > 0, "Should find entity classes");

        // Test transformed
        var transformed = classFileTransform.transformed();
        assertTrue(transformed.size() > 0, "Should transform classes");

        // Test that generated bytecode is valid
        byte[] bytecode = generator.generate();
        assertTrue(bytecode.length > 0, "Should generate non-empty bytecode");

        // Validate bytecode using ClassFile API (parsing validates structure)
        ClassModel classModel = ClassFile.of().parse(bytecode);

        assertEquals(className.replace('.', '/'), classModel.thisClass().asInternalName(),
                     "Generated class should have correct name");
        assertTrue(classModel.methods().size() > 0, "Generated class should have methods");
    }

}
